//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsoleEF62
{
    using System;
    using System.Collections.Generic;
    
    public partial class vAircraftToFlightsAndFlightPlan
    {
        public int AircraftFlightOrFlightPlanId { get; set; }
        public Nullable<int> AircraftId { get; set; }
        public string AircraftName { get; set; }
        public Nullable<int> FlightId { get; set; }
        public string FlightAlias { get; set; }
        public Nullable<int> FlightPlanId { get; set; }
        public string FlightPlanName { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> ModifiedById { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedLast { get; set; }
    }
}
